"""
Python Token Decryption for Urbex Frontend Tokens

This module provides functions to decrypt tokens generated by the frontend
encryption system (src/lib/encryption.ts).

Usage:
    from decrypt_token import decrypt_barmanpre
    
    # Decrypt a token from the frontend
    token = "your-encrypted-token-here"
    barmanpre = decrypt_barmanpre(token)
    print(f"Decrypted barmanpre: {barmanpre}")
"""

import base64
import urllib.parse
from typing import Optional


# Must match the key in frontend (src/lib/encryption.ts)
ENCRYPTION_KEY = 'URBEX_2024_SECURE_KEY_v1.0'


def caesar_shift(text: str, shift: int) -> str:
    """
    Apply Caesar cipher shift to text
    
    Args:
        text: Text to shift
        shift: Number of positions to shift (can be negative)
    
    Returns:
        Shifted text
    """
    result = ""
    for char in text:
        # Apply shift to all characters (matches frontend behavior)
        shifted_code = ord(char) + shift
        result += chr(shifted_code)
    return result


def xor_cipher(text: str, key: str) -> str:
    """
    Apply XOR cipher with key
    
    Args:
        text: Text to encrypt/decrypt
        key: Encryption key
    
    Returns:
        XOR result
    """
    result = ""
    for i, char in enumerate(text):
        text_code = ord(char)
        key_code = ord(key[i % len(key)])
        result += chr(text_code ^ key_code)
    return result


def decrypt_barmanpre(encrypted_token: str) -> Optional[str]:
    """
    Decrypt a barmanpre token from the frontend
    
    Args:
        encrypted_token: The encrypted token from the URL
    
    Returns:
        Original barmanpre string or None if decryption fails
    """
    try:
        print(f"🔓 Decrypting token: {encrypted_token[:20]}...")
        
        # Step 1: URL decode if needed
        if '%' in encrypted_token:
            encrypted_token = urllib.parse.unquote(encrypted_token)
        
        # Step 2: Restore URL-safe Base64
        base64_str = encrypted_token.replace('-', '+').replace('_', '/')
        
        # Add padding if needed
        while len(base64_str) % 4:
            base64_str += '='
        
        # Step 3: Base64 decode
        try:
            shifted = base64.b64decode(base64_str).decode('latin1')
        except Exception as e:
            print(f"❌ Base64 decode error: {e}")
            return try_fallback_decryption(encrypted_token)
        
        # Step 4: Reverse Caesar shift (-7)
        xor_result = caesar_shift(shifted, -7)
        
        # Step 5: Reverse XOR
        payload = xor_cipher(xor_result, ENCRYPTION_KEY)
        
        # Step 6: Extract barmanpre (ignore timestamp)
        parts = payload.split('|')
        if len(parts) >= 2:
            barmanpre = parts[0]
            print(f"✅ Token decrypted successfully: {barmanpre}")
            return barmanpre
        else:
            print("❌ Invalid payload format")
            return try_fallback_decryption(encrypted_token)
            
    except Exception as e:
        print(f"❌ Decryption error: {e}")
        return try_fallback_decryption(encrypted_token)


def try_fallback_decryption(encrypted_token: str) -> Optional[str]:
    """
    Try simple base64 decryption as fallback
    
    Args:
        encrypted_token: The encrypted token
    
    Returns:
        Decoded string or None if fallback also fails
    """
    try:
        print("⚠️ Trying fallback decryption...")
        
        # Restore URL-safe Base64
        base64_str = encrypted_token.replace('-', '+').replace('_', '/')
        
        # Add padding if needed
        while len(base64_str) % 4:
            base64_str += '='
        
        # Simple base64 decode
        fallback_result = base64.b64decode(base64_str).decode('utf-8')
        print(f"⚠️ Fallback decryption result: {fallback_result}")
        return fallback_result
        
    except Exception as e:
        print(f"❌ Fallback decryption also failed: {e}")
        return None


def is_valid_encrypted_token(encrypted_token: str) -> bool:
    """
    Validate if an encrypted string looks valid
    
    Args:
        encrypted_token: The encrypted string to validate
    
    Returns:
        True if it looks like a valid encrypted string
    """
    import re
    
    # Should be reasonable length and contain only URL-safe Base64 chars
    url_safe_base64_regex = re.compile(r'^[A-Za-z0-9\-_]+$')
    return (10 < len(encrypted_token) < 200 and 
            url_safe_base64_regex.match(encrypted_token) is not None)


def test_decryption():
    """Test the decryption with a known value"""
    print("🧪 Testing decryption...")
    
    # You can get a test token from the frontend console
    test_token = "your-test-token-here"  # Replace with actual token from frontend
    
    if test_token == "your-test-token-here":
        print("⚠️ Please replace 'test_token' with an actual encrypted token from the frontend")
        return
    
    result = decrypt_barmanpre(test_token)
    print(f"Test result: {result}")


# FastAPI integration example
def create_fastapi_endpoint():
    """
    Example of how to use this in a FastAPI endpoint
    """
    from fastapi import FastAPI, HTTPException, Query
    
    app = FastAPI()
    
    @app.get("/api/v1/property/detail")
    async def get_property_detail(token: str = Query(..., description="Encrypted barmanpre token")):
        """
        Get property details using encrypted token
        
        Args:
            token: Encrypted barmanpre token from frontend
        
        Returns:
            Property details
        """
        # Validate token format
        if not is_valid_encrypted_token(token):
            raise HTTPException(status_code=400, detail="Invalid token format")
        
        # Decrypt the token
        barmanpre = decrypt_barmanpre(token)
        if not barmanpre:
            raise HTTPException(status_code=400, detail="Failed to decrypt token")
        
        # Now use the barmanpre to get property details
        print(f"🔍 Getting property details for barmanpre: {barmanpre}")
        
        # Your property lookup logic here
        # property_data = get_property_from_database(barmanpre)
        
        return {
            "success": True,
            "barmanpre": barmanpre,
            "message": "Token decrypted successfully"
            # "data": property_data
        }
    
    return app


if __name__ == "__main__":
    # Test the decryption
    test_decryption()
