name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - feature/urbex-002

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm ci

    - name: Build and export
      run: npm run build
    
    - name: Deploy to S3
      run: aws s3 sync ./out s3://${{ secrets.S3_BUCKET_NAME }} --delete
      env:
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_USER_POOL_ID: ${{ secrets.AWS_USER_POOL_ID }}
        AWS_POOL_CLIENT_ID: ${{ secrets.AWS_POOL_CLIENT_ID }}
        SOURCE_DIR: 'out'

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}